name: eslint

on:
  push:
    branches:
      - master

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx